name: optimus_case
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Network
  dio: ^5.4.2+1 # HTTP client
  retrofit: ^4.1.0 # HTTP client generator
  
  # State management
  get_it: ^7.6.7 # Service locator
  provider: ^6.1.2 # State management
  
  # Utilities
  intl: ^0.19.0 # Date and number formatting
  flutter_svg: ^2.0.7 # SVG rendering
  cupertino_icons: ^1.0.8 # Cupertino icons
  device_info_plus: ^11.2.0 # Device information from OS
  flutter_screenutil: ^5.9.0 # Responsive UI
  shared_preferences: ^2.2.2 # Basic local data storage


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code generators
  build_runner: ^2.4.9 # Main code generator
  json_serializable: ^6.7.1 # JSON serializer for Retrofit package
  retrofit_generator: ^8.1.0 # Code generator for Retrofit package

flutter:

  uses-material-design: true

  assets:
    - assets/back.svg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
